name: devotionalapp
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'
  # '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  intl: ^0.18.1
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.3
  firebase_database: ^10.3.6


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic

    
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoSlab-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoSlab-ExtraBold.ttf
          weight: 800
